%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/minwoo/datasets/tum/rgbd_dataset_freiburg2_desk 

# camera intrinsics
# fr1
#camera.fx: 517.3
#camera.fy: 516.5
#camera.cx: 325.1
#camera.cy: 249.7

# fr2
camera.fx: 520.908620
camera.fy: 521.007327
camera.cx: 325.141442
camera.cy: 249.701764

camera.k1: 0.231222
camera.k2: -0.784899
camera.p1: -0.003257
camera.p2: -0.000105
camera.k3: 0.917205

camera.depth_scale: 5000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
